Add benchmark for day 04
This is failing at the moment and I haven't worked out why.

Benchmarking day04_part1thread 'main' panicked at src/day04.rs:16:16:
index out of bounds: the len is 0 but the index is 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Benchmarking day04_part1: Warming up for 3.0000 sthread 'main' panicked at 'Unexpected message FinishedBenchmarkGroup { group: "day04_part1" }', /Users/jabley/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-criterion-1.1.0/src/bench_target.rs:306:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at /Users/jabley/.cargo/registry/src/index.crates.io-6f17d22bba15001f/criterion-0.5.1/src/benchmark_group.rs:380:18:
called `Result::unwrap()` on an `Err` value: Io(Error { kind: UnexpectedEof, message: "failed to fill whole buffer" })
stack backtrace:
   0:        0x10229925c - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h7adefaad4a31afc0
   1:        0x10213651c - core::fmt::write::h381c0b0ce6ab972a
   2:        0x1022708dc - std::io::Write::write_fmt::h75af97148630d8d3
   3:        0x10229c8fc - std::sys::backtrace::BacktraceLock::print::h8baf33e22611de71
   4:        0x10229c778 - std::panicking::default_hook::{{closure}}::h369c7295ef58c5b1
   5:        0x10229cfbc - std::panicking::rust_panic_with_hook::h7d795911432661cb
   6:        0x10229c9c4 - std::panicking::begin_panic_handler::{{closure}}::h36f15310ecbde379
   7:        0x10229c934 - std::sys::backtrace::__rust_end_short_backtrace::heed121414170e0c7
   8:        0x10229c928 - _rust_begin_unwind
   9:        0x1022a8790 - core::panicking::panic_fmt::h17b1b80ec02ffd19
  10:        0x1022a8a38 - core::result::unwrap_failed::h6de8f20130c8e837
  11:        0x1020ec910 - core::ptr::drop_in_place<criterion::benchmark_group::BenchmarkGroup<criterion::measurement::WallTime>>::hd65b78925fb839df
  12:        0x1021d4e2c - day04_benchmark::main::h3366e0587a319ddc
  13:        0x1021da1c4 - std::sys::backtrace::__rust_begin_short_backtrace::h4b21ea1970da0732
  14:        0x1021d38e8 - _main
thread 'main' panicked at core/src/panicking.rs:229:5:
panic in a destructor during cleanup
thread caused non-unwinding panic. aborting.